/*
 * This file is generated by jOOQ.
 */
package com.migibert.embro.infrastructure.persistence.model.tables;


import com.migibert.embro.infrastructure.persistence.model.Keys;
import com.migibert.embro.infrastructure.persistence.model.Public;
import com.migibert.embro.infrastructure.persistence.model.enums.Role;
import com.migibert.embro.infrastructure.persistence.model.tables.OrganizationTable.OrganizationPath;
import com.migibert.embro.infrastructure.persistence.model.tables.records.InvitationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InvitationTable extends TableImpl<InvitationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.invitation</code>
     */
    public static final InvitationTable INVITATION = new InvitationTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvitationRecord> getRecordType() {
        return InvitationRecord.class;
    }

    /**
     * The column <code>public.invitation.id</code>.
     */
    public final TableField<InvitationRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.invitation.email</code>.
     */
    public final TableField<InvitationRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.invitation.invited_by</code>.
     */
    public final TableField<InvitationRecord, String> INVITED_BY = createField(DSL.name("invited_by"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.invitation.expires_at</code>.
     */
    public final TableField<InvitationRecord, LocalDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("(now() + '7 days'::interval)"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.invitation.organization_id</code>.
     */
    public final TableField<InvitationRecord, UUID> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.invitation.role</code>.
     */
    public final TableField<InvitationRecord, Role> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(Role.class), this, "");

    private InvitationTable(Name alias, Table<InvitationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InvitationTable(Name alias, Table<InvitationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.invitation</code> table reference
     */
    public InvitationTable(String alias) {
        this(DSL.name(alias), INVITATION);
    }

    /**
     * Create an aliased <code>public.invitation</code> table reference
     */
    public InvitationTable(Name alias) {
        this(alias, INVITATION);
    }

    /**
     * Create a <code>public.invitation</code> table reference
     */
    public InvitationTable() {
        this(DSL.name("invitation"), null);
    }

    public <O extends Record> InvitationTable(Table<O> path, ForeignKey<O, InvitationRecord> childPath, InverseForeignKey<O, InvitationRecord> parentPath) {
        super(path, childPath, parentPath, INVITATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InvitationPath extends InvitationTable implements Path<InvitationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InvitationPath(Table<O> path, ForeignKey<O, InvitationRecord> childPath, InverseForeignKey<O, InvitationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InvitationPath(Name alias, Table<InvitationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InvitationPath as(String alias) {
            return new InvitationPath(DSL.name(alias), this);
        }

        @Override
        public InvitationPath as(Name alias) {
            return new InvitationPath(alias, this);
        }

        @Override
        public InvitationPath as(Table<?> alias) {
            return new InvitationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<InvitationRecord> getPrimaryKey() {
        return Keys.INVITATION_PKEY;
    }

    @Override
    public List<ForeignKey<InvitationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INVITATION__FK_INVITATION_ORGANIZATION);
    }

    private transient OrganizationPath _organization;

    /**
     * Get the implicit join path to the <code>public.organization</code> table.
     */
    public OrganizationPath organization() {
        if (_organization == null)
            _organization = new OrganizationPath(this, Keys.INVITATION__FK_INVITATION_ORGANIZATION, null);

        return _organization;
    }

    @Override
    public InvitationTable as(String alias) {
        return new InvitationTable(DSL.name(alias), this);
    }

    @Override
    public InvitationTable as(Name alias) {
        return new InvitationTable(alias, this);
    }

    @Override
    public InvitationTable as(Table<?> alias) {
        return new InvitationTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InvitationTable rename(String name) {
        return new InvitationTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InvitationTable rename(Name name) {
        return new InvitationTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InvitationTable rename(Table<?> name) {
        return new InvitationTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvitationTable where(Condition condition) {
        return new InvitationTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvitationTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvitationTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvitationTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InvitationTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InvitationTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InvitationTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InvitationTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvitationTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InvitationTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
