/*
 * This file is generated by jOOQ.
 */
package com.migibert.embro.infrastructure.persistence.model.tables;


import com.migibert.embro.infrastructure.persistence.model.Keys;
import com.migibert.embro.infrastructure.persistence.model.Public;
import com.migibert.embro.infrastructure.persistence.model.tables.OrganizationTable.OrganizationPath;
import com.migibert.embro.infrastructure.persistence.model.tables.records.PositionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PositionTable extends TableImpl<PositionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.position</code>
     */
    public static final PositionTable POSITION = new PositionTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PositionRecord> getRecordType() {
        return PositionRecord.class;
    }

    /**
     * The column <code>public.position.id</code>.
     */
    public final TableField<PositionRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.position.organization_id</code>.
     */
    public final TableField<PositionRecord, UUID> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.position.name</code>.
     */
    public final TableField<PositionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private PositionTable(Name alias, Table<PositionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PositionTable(Name alias, Table<PositionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.position</code> table reference
     */
    public PositionTable(String alias) {
        this(DSL.name(alias), POSITION);
    }

    /**
     * Create an aliased <code>public.position</code> table reference
     */
    public PositionTable(Name alias) {
        this(alias, POSITION);
    }

    /**
     * Create a <code>public.position</code> table reference
     */
    public PositionTable() {
        this(DSL.name("position"), null);
    }

    public <O extends Record> PositionTable(Table<O> path, ForeignKey<O, PositionRecord> childPath, InverseForeignKey<O, PositionRecord> parentPath) {
        super(path, childPath, parentPath, POSITION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PositionPath extends PositionTable implements Path<PositionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PositionPath(Table<O> path, ForeignKey<O, PositionRecord> childPath, InverseForeignKey<O, PositionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PositionPath(Name alias, Table<PositionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PositionPath as(String alias) {
            return new PositionPath(DSL.name(alias), this);
        }

        @Override
        public PositionPath as(Name alias) {
            return new PositionPath(alias, this);
        }

        @Override
        public PositionPath as(Table<?> alias) {
            return new PositionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PositionRecord> getPrimaryKey() {
        return Keys.POSITION_PKEY;
    }

    @Override
    public List<ForeignKey<PositionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.POSITION__FK_POSITION_ORGANIZATION);
    }

    private transient OrganizationPath _organization;

    /**
     * Get the implicit join path to the <code>public.organization</code> table.
     */
    public OrganizationPath organization() {
        if (_organization == null)
            _organization = new OrganizationPath(this, Keys.POSITION__FK_POSITION_ORGANIZATION, null);

        return _organization;
    }

    @Override
    public PositionTable as(String alias) {
        return new PositionTable(DSL.name(alias), this);
    }

    @Override
    public PositionTable as(Name alias) {
        return new PositionTable(alias, this);
    }

    @Override
    public PositionTable as(Table<?> alias) {
        return new PositionTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PositionTable rename(String name) {
        return new PositionTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PositionTable rename(Name name) {
        return new PositionTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PositionTable rename(Table<?> name) {
        return new PositionTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PositionTable where(Condition condition) {
        return new PositionTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PositionTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PositionTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PositionTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PositionTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PositionTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PositionTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PositionTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PositionTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PositionTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
