/*
 * This file is generated by jOOQ.
 */
package com.migibert.embro.infrastructure.persistence.model.tables;


import com.migibert.embro.infrastructure.persistence.model.Keys;
import com.migibert.embro.infrastructure.persistence.model.Public;
import com.migibert.embro.infrastructure.persistence.model.tables.OrganizationTable.OrganizationPath;
import com.migibert.embro.infrastructure.persistence.model.tables.records.SeniorityRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SeniorityTable extends TableImpl<SeniorityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.seniority</code>
     */
    public static final SeniorityTable SENIORITY = new SeniorityTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeniorityRecord> getRecordType() {
        return SeniorityRecord.class;
    }

    /**
     * The column <code>public.seniority.id</code>.
     */
    public final TableField<SeniorityRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.seniority.organization_id</code>.
     */
    public final TableField<SeniorityRecord, UUID> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.seniority.name</code>.
     */
    public final TableField<SeniorityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private SeniorityTable(Name alias, Table<SeniorityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SeniorityTable(Name alias, Table<SeniorityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.seniority</code> table reference
     */
    public SeniorityTable(String alias) {
        this(DSL.name(alias), SENIORITY);
    }

    /**
     * Create an aliased <code>public.seniority</code> table reference
     */
    public SeniorityTable(Name alias) {
        this(alias, SENIORITY);
    }

    /**
     * Create a <code>public.seniority</code> table reference
     */
    public SeniorityTable() {
        this(DSL.name("seniority"), null);
    }

    public <O extends Record> SeniorityTable(Table<O> path, ForeignKey<O, SeniorityRecord> childPath, InverseForeignKey<O, SeniorityRecord> parentPath) {
        super(path, childPath, parentPath, SENIORITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SeniorityPath extends SeniorityTable implements Path<SeniorityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SeniorityPath(Table<O> path, ForeignKey<O, SeniorityRecord> childPath, InverseForeignKey<O, SeniorityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SeniorityPath(Name alias, Table<SeniorityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SeniorityPath as(String alias) {
            return new SeniorityPath(DSL.name(alias), this);
        }

        @Override
        public SeniorityPath as(Name alias) {
            return new SeniorityPath(alias, this);
        }

        @Override
        public SeniorityPath as(Table<?> alias) {
            return new SeniorityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SeniorityRecord> getPrimaryKey() {
        return Keys.SENIORITY_PKEY;
    }

    @Override
    public List<ForeignKey<SeniorityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SENIORITY__FK_SENIORITY_ORGANIZATION);
    }

    private transient OrganizationPath _organization;

    /**
     * Get the implicit join path to the <code>public.organization</code> table.
     */
    public OrganizationPath organization() {
        if (_organization == null)
            _organization = new OrganizationPath(this, Keys.SENIORITY__FK_SENIORITY_ORGANIZATION, null);

        return _organization;
    }

    @Override
    public SeniorityTable as(String alias) {
        return new SeniorityTable(DSL.name(alias), this);
    }

    @Override
    public SeniorityTable as(Name alias) {
        return new SeniorityTable(alias, this);
    }

    @Override
    public SeniorityTable as(Table<?> alias) {
        return new SeniorityTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SeniorityTable rename(String name) {
        return new SeniorityTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SeniorityTable rename(Name name) {
        return new SeniorityTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SeniorityTable rename(Table<?> name) {
        return new SeniorityTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SeniorityTable where(Condition condition) {
        return new SeniorityTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SeniorityTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SeniorityTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SeniorityTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SeniorityTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SeniorityTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SeniorityTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SeniorityTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SeniorityTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SeniorityTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
