/*
 * This file is generated by jOOQ.
 */
package com.migibert.embro.infrastructure.persistence.model.tables;


import com.migibert.embro.infrastructure.persistence.model.Keys;
import com.migibert.embro.infrastructure.persistence.model.Public;
import com.migibert.embro.infrastructure.persistence.model.tables.CollaboratorTable.CollaboratorPath;
import com.migibert.embro.infrastructure.persistence.model.tables.OrganizationTable.OrganizationPath;
import com.migibert.embro.infrastructure.persistence.model.tables.TeamCollaboratorTable.TeamCollaboratorPath;
import com.migibert.embro.infrastructure.persistence.model.tables.records.TeamRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TeamTable extends TableImpl<TeamRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.team</code>
     */
    public static final TeamTable TEAM = new TeamTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamRecord> getRecordType() {
        return TeamRecord.class;
    }

    /**
     * The column <code>public.team.id</code>.
     */
    public final TableField<TeamRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.team.organization_id</code>.
     */
    public final TableField<TeamRecord, UUID> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.team.name</code>.
     */
    public final TableField<TeamRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private TeamTable(Name alias, Table<TeamRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TeamTable(Name alias, Table<TeamRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.team</code> table reference
     */
    public TeamTable(String alias) {
        this(DSL.name(alias), TEAM);
    }

    /**
     * Create an aliased <code>public.team</code> table reference
     */
    public TeamTable(Name alias) {
        this(alias, TEAM);
    }

    /**
     * Create a <code>public.team</code> table reference
     */
    public TeamTable() {
        this(DSL.name("team"), null);
    }

    public <O extends Record> TeamTable(Table<O> path, ForeignKey<O, TeamRecord> childPath, InverseForeignKey<O, TeamRecord> parentPath) {
        super(path, childPath, parentPath, TEAM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TeamPath extends TeamTable implements Path<TeamRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TeamPath(Table<O> path, ForeignKey<O, TeamRecord> childPath, InverseForeignKey<O, TeamRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TeamPath(Name alias, Table<TeamRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TeamPath as(String alias) {
            return new TeamPath(DSL.name(alias), this);
        }

        @Override
        public TeamPath as(Name alias) {
            return new TeamPath(alias, this);
        }

        @Override
        public TeamPath as(Table<?> alias) {
            return new TeamPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TeamRecord> getPrimaryKey() {
        return Keys.TEAM_PKEY;
    }

    @Override
    public List<ForeignKey<TeamRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TEAM__FK_TEAM_ORGANIZATION);
    }

    private transient OrganizationPath _organization;

    /**
     * Get the implicit join path to the <code>public.organization</code> table.
     */
    public OrganizationPath organization() {
        if (_organization == null)
            _organization = new OrganizationPath(this, Keys.TEAM__FK_TEAM_ORGANIZATION, null);

        return _organization;
    }

    private transient TeamCollaboratorPath _teamCollaborator;

    /**
     * Get the implicit to-many join path to the
     * <code>public.team_collaborator</code> table
     */
    public TeamCollaboratorPath teamCollaborator() {
        if (_teamCollaborator == null)
            _teamCollaborator = new TeamCollaboratorPath(this, null, Keys.TEAM_COLLABORATOR__FK_TEAM_COLLABORATOR_TEAM.getInverseKey());

        return _teamCollaborator;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.collaborator</code> table
     */
    public CollaboratorPath collaborator() {
        return teamCollaborator().collaborator();
    }

    @Override
    public TeamTable as(String alias) {
        return new TeamTable(DSL.name(alias), this);
    }

    @Override
    public TeamTable as(Name alias) {
        return new TeamTable(alias, this);
    }

    @Override
    public TeamTable as(Table<?> alias) {
        return new TeamTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamTable rename(String name) {
        return new TeamTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamTable rename(Name name) {
        return new TeamTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamTable rename(Table<?> name) {
        return new TeamTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamTable where(Condition condition) {
        return new TeamTable(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamTable whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamTable whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
