/*
 * This file is generated by jOOQ.
 */
package com.migibert.embro.infrastructure.persistence.model;


import com.migibert.embro.infrastructure.persistence.model.tables.CollaboratorSkillTable;
import com.migibert.embro.infrastructure.persistence.model.tables.CollaboratorTable;
import com.migibert.embro.infrastructure.persistence.model.tables.FlywaySchemaHistoryTable;
import com.migibert.embro.infrastructure.persistence.model.tables.OrganizationTable;
import com.migibert.embro.infrastructure.persistence.model.tables.SeniorityTable;
import com.migibert.embro.infrastructure.persistence.model.tables.SkillTable;
import com.migibert.embro.infrastructure.persistence.model.tables.TeamCollaboratorTable;
import com.migibert.embro.infrastructure.persistence.model.tables.TeamTable;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.collaborator</code>.
     */
    public final CollaboratorTable COLLABORATOR = CollaboratorTable.COLLABORATOR;

    /**
     * The table <code>public.collaborator_skill</code>.
     */
    public final CollaboratorSkillTable COLLABORATOR_SKILL = CollaboratorSkillTable.COLLABORATOR_SKILL;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistoryTable FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.organization</code>.
     */
    public final OrganizationTable ORGANIZATION = OrganizationTable.ORGANIZATION;

    /**
     * The table <code>public.seniority</code>.
     */
    public final SeniorityTable SENIORITY = SeniorityTable.SENIORITY;

    /**
     * The table <code>public.skill</code>.
     */
    public final SkillTable SKILL = SkillTable.SKILL;

    /**
     * The table <code>public.team</code>.
     */
    public final TeamTable TEAM = TeamTable.TEAM;

    /**
     * The table <code>public.team_collaborator</code>.
     */
    public final TeamCollaboratorTable TEAM_COLLABORATOR = TeamCollaboratorTable.TEAM_COLLABORATOR;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CollaboratorTable.COLLABORATOR,
            CollaboratorSkillTable.COLLABORATOR_SKILL,
            FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY,
            OrganizationTable.ORGANIZATION,
            SeniorityTable.SENIORITY,
            SkillTable.SKILL,
            TeamTable.TEAM,
            TeamCollaboratorTable.TEAM_COLLABORATOR
        );
    }
}
