/*
 * This file is generated by jOOQ.
 */
package com.migibert.embro.infrastructure.persistence.model;


import com.migibert.embro.infrastructure.persistence.model.tables.CollaboratorSkillTable;
import com.migibert.embro.infrastructure.persistence.model.tables.CollaboratorTable;
import com.migibert.embro.infrastructure.persistence.model.tables.FlywaySchemaHistoryTable;
import com.migibert.embro.infrastructure.persistence.model.tables.OrganizationTable;
import com.migibert.embro.infrastructure.persistence.model.tables.RoleTable;
import com.migibert.embro.infrastructure.persistence.model.tables.SeniorityTable;
import com.migibert.embro.infrastructure.persistence.model.tables.SkillTable;
import com.migibert.embro.infrastructure.persistence.model.tables.TeamCollaboratorTable;
import com.migibert.embro.infrastructure.persistence.model.tables.TeamTable;
import com.migibert.embro.infrastructure.persistence.model.tables.UserOrganizationTable;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.collaborator</code>.
     */
    public static final CollaboratorTable COLLABORATOR = CollaboratorTable.COLLABORATOR;

    /**
     * The table <code>public.collaborator_skill</code>.
     */
    public static final CollaboratorSkillTable COLLABORATOR_SKILL = CollaboratorSkillTable.COLLABORATOR_SKILL;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistoryTable FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.organization</code>.
     */
    public static final OrganizationTable ORGANIZATION = OrganizationTable.ORGANIZATION;

    /**
     * The table <code>public.role</code>.
     */
    public static final RoleTable ROLE = RoleTable.ROLE;

    /**
     * The table <code>public.seniority</code>.
     */
    public static final SeniorityTable SENIORITY = SeniorityTable.SENIORITY;

    /**
     * The table <code>public.skill</code>.
     */
    public static final SkillTable SKILL = SkillTable.SKILL;

    /**
     * The table <code>public.team</code>.
     */
    public static final TeamTable TEAM = TeamTable.TEAM;

    /**
     * The table <code>public.team_collaborator</code>.
     */
    public static final TeamCollaboratorTable TEAM_COLLABORATOR = TeamCollaboratorTable.TEAM_COLLABORATOR;

    /**
     * The table <code>public.user_organization</code>.
     */
    public static final UserOrganizationTable USER_ORGANIZATION = UserOrganizationTable.USER_ORGANIZATION;
}
