/*
 * This file is generated by jOOQ.
 */
package com.migibert.embro.infrastructure.persistence.model.tables.records;


import com.migibert.embro.infrastructure.persistence.model.tables.CollaboratorSkillTable;

import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CollaboratorSkillRecord extends UpdatableRecordImpl<CollaboratorSkillRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.collaborator_skill.organization_id</code>.
     */
    public void setOrganizationId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.collaborator_skill.organization_id</code>.
     */
    public UUID getOrganizationId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.collaborator_skill.collaborator_id</code>.
     */
    public void setCollaboratorId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.collaborator_skill.collaborator_id</code>.
     */
    public UUID getCollaboratorId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.collaborator_skill.skill_id</code>.
     */
    public void setSkillId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.collaborator_skill.skill_id</code>.
     */
    public UUID getSkillId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.collaborator_skill.proficiency</code>.
     */
    public void setProficiency(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.collaborator_skill.proficiency</code>.
     */
    public Integer getProficiency() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CollaboratorSkillRecord
     */
    public CollaboratorSkillRecord() {
        super(CollaboratorSkillTable.COLLABORATOR_SKILL);
    }

    /**
     * Create a detached, initialised CollaboratorSkillRecord
     */
    public CollaboratorSkillRecord(UUID organizationId, UUID collaboratorId, UUID skillId, Integer proficiency) {
        super(CollaboratorSkillTable.COLLABORATOR_SKILL);

        setOrganizationId(organizationId);
        setCollaboratorId(collaboratorId);
        setSkillId(skillId);
        setProficiency(proficiency);
        resetChangedOnNotNull();
    }
}
