name: release-backend
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: ./backend
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: sa
          POSTGRES_PASSWORD: pwd
          POSTGRES_DB: embro-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 21 Temurin
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run tests
        run: mvn -Pdev test
      - name: Build production artifact
        run: mvn -Pprod package
      - name: Build Docker image
        run: docker build -t embro-api .
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
      - name: Building and pushing the image to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          registry: gcr.io
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          image_name: embro-api
          image_tag: ${{ github.sha }}, latest
          dockerfile: ./Dockerfile
          context: .