name: release-backend
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: ./backend
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: sa
          POSTGRES_PASSWORD: pwd
          POSTGRES_DB: embro-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21 Temurin
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: mvn -Pdev test

      - name: Build production artifact
        run: mvn -Pprod package

      - name: Build Docker image
        run: docker build -t embro-api .

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker for GCR
        run: gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true          
          tags: |
            gcr.io/${{secrets.GCP_PROJECT_ID}}/embro-api:latest
            gcr.io/${{secrets.GCP_PROJECT_ID}}/embro-api:${{github.sha}}
          file: Dockerfile