name: release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-backend:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: ./backend
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: sa
          POSTGRES_PASSWORD: pwd
          POSTGRES_DB: embro-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21 Temurin
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: mvn -Pdev test

      - name: Build production artifact
        run: mvn -Pprod package

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker for Artifact Repository
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set date
        id: date
        run: echo "::set-output name=date::$(date '+%Y%m%d%H%M')"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            europe-west1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/embro/embro-api:latest
            europe-west1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/embro/embro-api:${{ steps.date.outputs.date }}
  
  release-frontend:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: ./frontend/embro
    env:
      REACT_APP_EMBRO_API_BASE_URL: ${{ secrets.BACKEND_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build production artifact
        run: npm run build
      
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker for Artifact Repository
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set date
        id: date
        run: echo "::set-output name=date::$(date '+%Y%m%d%H%M')"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/embro
          push: true
          tags: |
            europe-west1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/embro/embro-ui:latest
            europe-west1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/embro/embro-ui:${{ steps.date.outputs.date }}

  release-infrastructure:
    needs:
      - release-backend
      - release-frontend
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.9.5
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: TF_VAR_project_id=${{ secrets.GCP_PROJECT_ID }} terraform apply -auto-approve